Change default connection to database to use host different than dock…
MariaDB/feedback-plugin-backend pull request #3
Opened 2022-05-30 14:53 UTC by an3l

…er container

- After setting up the virtual environment for the project
  (note missing instruction how to work locally with venv in `Readme.md`) and
  after running the `makemigrations --dry-run` or starting the webserver,
  application is trying to connect with hardcoded hostname `db` used from Dockerfile
- This patch allows to add multiple hostname from environment variable separed
  by delimiter (I liked `,`) and since the create type in settings.py is `list` type
  it is free to use first value from a list.
- Proof
* No patch
```
$ export DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
$ ./manage.py makemigrations --dry-run
/home/anel/mariadb/feedback-plugin-backend/env/lib/python3.8/site-packages/django/core/management/commands/makemigrations.py:105:
  RuntimeWarning: Got an error checking a consistent migration history performed for database connection 'default': (2005, "Unknown MySQL server host 'db' (-3)")
  warnings.warn(
Migrations for 'feedback_plugin':
  feedback_plugin/migrations/0002_alter_rawdata_upload_time.py
    - Alter field upload_time on rawdata
```
* With patch
```
$ ./manage.py makemigrations --dry-run
Migrations for 'feedback_plugin':
  feedback_plugin/migrations/0002_alter_rawdata_upload_time.py
    - Alter field upload_time on rawdata
```
- Also server gets started correctly
```
$ ./manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).

You have 19 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, feedback_plugin, sessions.
Run 'python manage.py migrate' to apply them.
May 30, 2022 - 14:51:50
Django version 3.2.13, using settings 'feedback_plugin.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```

2022-05-31 01:57 UTC, grooverdan commented
`DJANGO_ALLOWED_HOSTS` and the database host are actually different concepts. Why not `os.environ['DJANGO_DB_HOST']`

2022-05-31 06:25 UTC, cvicentiu requested changes
@an3l I like the first change where one allows multiple hosts in DJANGO's allow hosts.
I am ok with having a change-able db host via an environment variable. You can do as Daniel suggests, but please also update

docker/.env file if you do so.

2022-05-31 14:43 UTC, an3l commented
Ok based on documentation [allowed_host](https://docs.djangoproject.com/en/4.0/ref/settings/#allowed-hosts) is used for other purposes (may be empty when `DEBUG=true`).
Django documentation for [setting up MySQL](https://docs.djangoproject.com/en/4.0/ref/databases/#connecting-to-the-database) has an example  of usage of configuration file in [options](https://docs.djangoproject.com/en/4.0/ref/settings/#std:setting-OPTIONS) over [NAME](https://docs.djangoproject.com/en/4.0/ref/settings/#name), [HOST](https://docs.djangoproject.com/en/4.0/ref/settings/#host), etc , however I don't want to write the tweaks to populate configuration file with variable parameters like environment databases.
Have updated the patch @cvicentiu

2023-04-04 05:46 UTC, cvicentiu commented
Closing this as currently the deployment relies on docker-compose for full stack deployment. We will make these changes when we need to have a DB run on a different host.

We will keep using square brackets for environment variable fetching to highlight bugs. If an environment variable is missing, we want the code to throw an error, not silently continue.

2023-04-04 05:46 UTC, closed without merging